{% set name = "python-utils" %}
{% set version = "3.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 63a2ad8d36c6432978833a77cfa7d310af9bbfa9e837dcf828aac584d71f9ded

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - pytest
  run:
    - python >=3.6

test:
  imports:
    - python_utils
    - python_utils.converters
    - python_utils.formatters
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/WoLpH/python-utils
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Python Utils is a collection of small Python functions and classes which make common patterns shorter and easier.
  description: |
    Python Utils is a collection of small Python functions and classes which
    make common patterns shorter and easier. It is by no means a complete
    collection but it has served me quite a bit in the past and I will keep
    extending it.  One of the libraries using Python Utils is Django Utils.
  doc_url: http://python-utils.readthedocs.io/
  dev_url: https://github.com/WoLpH/python-utils

extra:
  recipe-maintainers:
    - maartenbreddels
    - WoLpH
    - stuertz
