travis:
  secure:
    BINSTAR_TOKEN: X7G6wnpuWHyTTmLreFCqNuUUtypk7Nk5n7HOKMiVcaFQ7Td7GW3Wde/H+tAKeLKFXxKuBMH4KVbOXzaq7eOqkNZHWCK17ghdko0FcSKebfebZ48fON0OJ/VDG+znD1gbTrV9yySLP7NZR9CZQt9Vp6y5OG0wceojsEfjd6get4LLVdezCAr6dDXYKmaT6VNjweFk4B/lzzJQ+KF9jHUB52smHy3CpZAjek5QhB+HCU5X66B/P51/1Wgn2TKux7hiBQul4x2dErDZKJ2hDa4ES3DfvQ2ktARUdWt/pz1kg6jtQ6FCU90KY7tK+DjX1Au05DP60Ez8qJxoRo6W6njHHu6odCBy2S0L8l8fT7gwHS/e3076lF2jepzrzKVP6WQuLmbaCICd9L6VDsIbSI6mV1aYeMkTyx9G4xuFzEPFgMUqtm9Wn3sDn1mKSMve/FVAeTLZWT4+RCVP0fgfmOMdK8aTcIxU14d+cA06IrB3F4jTc9uMbUEVmIXqTsuOLOkjD8agVSM6HH493qukjp22VF+x1zhBRVJ6k1JgwiLO7taQJy2A01u98FMUWngORUUNUDa/46fvkNSSjbH9Fa0C2YCPCLg7XpeQhqvt+9TOkc+pQj0KfiWx1Z2eB9ERMxstKxx7RypP+qvV5MgT9rdzCF9mqJlVmlxebNpemNiF/LU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
